# ML & Model Related
- label:  "model-training"
  any: 
    - changed-files: 
        - any-glob-patterns:
            - "training_programs/**"
            - "models/**"
            - "models_seqgen/**"
            - "*.py"

- label: "inference"
  any:
    - changed-files:
        - any-glob-patterns:
            - "inference_folder/**"

- label: "preprocessing"
  any:
    - changed-files:
        - any-glob-patterns:
            - "preprocessing/**"
            - "preprocessing_output/**"

- label: "data"
  any:
    - changed-files:
        - any-glob-patterns:
            - "data/**"

# RISC-V & Compiler Related
- label: "compiler-optimization"
  any:
    - changed-files:
        - any-glob-patterns:
            - "**/*.c"
            - "**/*.h"
            - "tools/**"

# Documentation
- label: "documentation"
  any:
    - changed-files:
        - any-glob-patterns:
            - "*.md"
            - "iris-website/**"

# Development & Infrastructure
- label: "ci-cd"
  any: 
    - changed-files:
        - any-glob-patterns: 
            - ".github/workflows/**"
            - ".github/labeler.yml"

- label: "devops"
  any:
    - changed-files:
        - any-glob-patterns:
            - ".github/**"
            - ".vscode/**"
            - ".gitignore"
            - ".gitattributes"

# Configuration
- label: "configuration"
  any:
    - changed-files:
        - any-glob-patterns:
            - "**/*.yml"
            - "**/*.yaml"
            - "**/*.json"
            - "**/*.toml"

# Code Quality & Type
- label: "enhancement"
  all:
    - body:  ["feature", "feature request", "enhancement"]

- label: "bug"
  all:
    - body: ["bug", "fix", "issue"]

- label: "research"
  all:
    - body: ["research", "experimental", "investigation"]

# Specific Components (based on directory structure)
- label: "logs-metrics"
  any:
    - changed-files:
        - any-glob-patterns:
            - "logs/**"

- label: "size"
  all:
    - body: ["passformer_binary_size"]

- label: "runtime"
  all:
    - body: ["passformer_runtime"]
